#############################################################################
# Cloud Security Demo - Insecure Kubernetes Configuration
# 
# Insecure overlay including:
# - No network policies
# - No resource limits
# - Privileged containers
# - Minimal security context
#############################################################################

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudsecdemo

bases:
  - ../../base

# Patch the deployment with insecure configurations
patchesStrategicMerge:
  - deployment-insecure-patch.yaml

# ConfigMap modifications
configMapGenerator:
  - name: cloudsecdemo-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - ENABLE_AUDIT=false
      - SECURE_MODE=false

---
# deployment-insecure-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsecdemo-app
spec:
  template:
    spec:
      # No securityContext specified
      containers:
      - name: app
        # Remove resource limits
        resources: {}
        # Remove probes for demonstration
        livenessProbe: null
        readinessProbe: null
        # Allow privileged operations
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
          capabilities:
            add:
              - ALL
        # Add insecure volume mount
        volumeMounts:
        - name: host-volume
          mountPath: /host
      volumes:
      - name: host-volume
        hostPath:
          path: /
          type: Directory

---
# service-patch.yaml
apiVersion: v1
kind: Service
metadata:
  name: cloudsecdemo-service
spec:
  # Change to NodePort for direct access
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: 30080
